---
author: Rayne Aurit
title: Resume
format:
  classic-cv-pdf: default
cvfooter:
  left: "https://raurit.github.io/portfolio/"
  right: "https://github.com/raurit"
cvcolor: 58748F #without `#`
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Status
    left: Student at the Universty of Nebraska-Lincoln
    right: Lincoln, NE
  - title: Field
    left: Statistics and Data Analytics, Computer Science
    right: auritrayne@gmail.com
  - title: Techs
    left: R, SAS, Python, Java, C, C#
    right: (402)490-6869
execute:
  echo: false
---

```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}
```

# Summary



# Experience


```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details, ~tasks,
    "Design Studio Associate", "University of Nebraska-Lincoln", "Aug. 2025 - Present",
    "Jeffrey S. Raikes School of Computer Science and Management", c("Developing an agentic AI framework to assist with manual processing and administrative tasks utilizing computer vision for corporate sponsor", "Communicating with sponsors, stakeholders, and academic leads to establish clear goals and objectives to execute a defined vision statement"),
    "AI in STEM Education Intern", "Nebraska Extension, 4-H", "May 2025 - Present",
    "Positive youth development for Nebraskans", c("Teaching members of the youth ages 8-18 in the focus areas of science, technology, engineering, and math", "Creating learning modules to assist in learning in statistics, data science, artificial intelligence, and computer science", "Utilizing CodePen to create youth-friendly UI illustrating written lesson plans"),
    "Post Doctoral Researcher", "ETH Zurich", "Nov. 2017 - Aug. 2018", "Chair of Social Networks", c("Developing new methods to analyze social networks", "Implementing methods in libraries", "Gathering and analyzing large datsets from Social Media APIs"),
    "Post Doctoral Researcher", "University of Konstanz", "Oct. 2015 - Oct. 2017", "Department of Computer & Information Science", c("Developing new methods to analyze social networks", "Implementing methods in libraries", "Webscraping and harmonizing a large corpus of football data"),
    "Ph.D. Candidate", "University of Konstanz", "Nov. 2012 - Sep. 2015", "Department of Computer & Information Science", c("Developing new methods to analyze social networks", "Implementing methods in libraries")
) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "tasks")
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "Ph.D. in Computer Science", "University of Konstanz", "Konstanz, Germany", "Nov. 2012 - Sep. 2015", c("Thesis: A Positional Approach for Network Centrality", "Developed and implemented new methods to assess network centrality"),
    "Diploma in Business Mathematics", "KIT", "Karlsruhe, Germany", "Sep. 2006 - Jul. 2012", c("Thesis: Modularity Maximization", "Implementation and comparison of different clustering algorithms using Matlab")
) |>
    cvevents(when = "dates", what = "degree", where = "loc", details = "details")
```
